version: "3.3"

services:
  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - "8120:80"